# Generated by Django 4.1.3 on 2022-11-25 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='approval',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ExtUser',
        ),
    ]
