# Generated by Django 4.1.3 on 2022-12-16 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsforseats',
            name='seats_requested',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
