# Generated by Django 4.1.3 on 2022-12-16 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_requestsforseats_seats_requested'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestsforseats',
            name='Room_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='requestsforseats',
            name='seats_requested',
            field=models.BooleanField(blank=True, default=0, null=True),
        ),
    ]
